import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {GLTFExporter} from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/exporters/GLTFExporter.js';
import {CONFIG} from './config.js';

const KEY='hyperstream_market_v1';
const demoListings=[
{id:'m1',name:'Neon Relic',category:'Artifact',rarity:'Epic',price:0.08,icon:'◈',seller:'HyperStream',created:Date.now()-900000},
{id:'m2',name:'Quantum Bloom',category:'Hologram',rarity:'Rare',price:0.12,icon:'✦',seller:'HyperStream',created:Date.now()-3600000},
{id:'m3',name:'Voxel Fox',category:'Creature',rarity:'Legendary',price:0.25,icon:'◉',seller:'HyperStream',created:Date.now()-7200000},
{id:'m4',name:'Dimensional Strata',category:'Environment',rarity:'Epic',price:0.18,icon:'◇',seller:'HyperStream',created:Date.now()-86400000},
{id:'m5',name:'Chrome Node',category:'Voxel',rarity:'Common',price:0.04,icon:'⬡',seller:'HyperStream',created:Date.now()-172800000},
{id:'m6',name:'Luma Core',category:'Hologram',rarity:'Rare',price:0.10,icon:'●',seller:'HyperStream',created:Date.now()-259200000}
];
let myLibrary=[],myListings=[],activityFeed=[];
let scene,camera,renderer,mesh,stream=null,frameTimer=null;
const $=id=>document.getElementById(id);
const live=()=>Boolean(CONFIG.contractAddress&&((CONFIG.pinataJwt)||(CONFIG.pinataApiKey&&CONFIG.pinataSecretKey)));
function persist(){localStorage.setItem(KEY,JSON.stringify({myLibrary,myListings,activityFeed}));}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');myLibrary=x.myLibrary||[];myListings=x.myListings||[];activityFeed=x.activityFeed||[]}catch{myLibrary=[];myListings=[];activityFeed=[]}}
function relative(ts){const s=Math.max(1,Math.floor((Date.now()-ts)/1000));if(s<60)return `${s}s ago`;const m=Math.floor(s/60);if(m<60)return `${m}m ago`;const h=Math.floor(m/60);if(h<24)return `${h}h ago`;return `${Math.floor(h/24)}d ago`}
function log(text){activityFeed.unshift({text,time:Date.now()});activityFeed=activityFeed.slice(0,100);persist()}
function allListings(){return [...demoListings,...myListings.filter(x=>x.id.startsWith('user-'))]}
function render(){const tab=document.querySelector('.tab.active')?.dataset.tab||'browse';$('browse-tools').style.display=tab==='browse'?'grid':'none';const list=$('market-list');list.textContent='';$('market-empty').hidden=true;if(tab==='browse')renderBrowse(list);if(tab==='listings')renderMine(list);if(tab==='library')renderLibrary(list);if(tab==='activity')renderActivity(list);$('listing-count').textContent=tab==='browse'?`${list.children.length} items`:''}
function card(item,actionText,action){const c=document.createElement('article');c.className='market-card';const t=document.createElement('div');t.className='card-thumb';t.textContent=item.icon||'✦';const b=document.createElement('div');b.className='card-body';const n=document.createElement('div');n.className='card-title';n.textContent=item.name;const meta=document.createElement('div');meta.className='card-meta';const cat=document.createElement('span');cat.textContent=item.category;const rar=document.createElement('span');rar.className='rarity';rar.textContent=item.rarity||'Rare';meta.append(cat,rar);const foot=document.createElement('div');foot.className='card-foot';const p=document.createElement('span');p.className='price';p.textContent=`${Number(item.price).toFixed(3)} MATIC`;const btn=document.createElement('button');btn.className='small primary';btn.textContent=actionText;btn.addEventListener('click',action);foot.append(p,btn);b.append(n,meta,foot);c.append(t,b);return c}
function renderBrowse(list){let a=allListings();const q=$('market-search').value.trim().toLowerCase(),cat=$('market-category').value,sort=$('market-sort').value;a=a.filter(x=>(!q||x.name.toLowerCase().includes(q)||x.category.toLowerCase().includes(q))&&(cat==='all'||x.category===cat));a.sort((x,y)=>sort==='price-low'?x.price-y.price:sort==='price-high'?y.price-x.price:sort==='name'?x.name.localeCompare(y.name):y.created-x.created);a.forEach(x=>list.append(card(x,live()?'Buy':'Buy (Demo)',()=>buy(x.id))))}
function renderMine(list){if(!myListings.length)return empty('No listings yet. List your current scan to see it here.');myListings.forEach(x=>list.append(card(x,'Cancel',()=>cancelListing(x.id))))}
function renderLibrary(list){if(!myLibrary.length)return empty('Your library is empty. Demo purchases will appear here.');myLibrary.forEach(x=>list.append(card(x,'Owned',()=>{})))}
function renderActivity(list){if(!activityFeed.length)return empty('No activity yet.');activityFeed.forEach(x=>{const row=document.createElement('div');row.className='activity-item';const a=document.createElement('strong');a.textContent=x.text;const b=document.createElement('span');b.textContent=relative(x.time);row.append(a,b);list.append(row)})}
function empty(text){$('market-empty').hidden=false;$('market-empty').textContent=text}
function buy(id){const item=allListings().find(x=>x.id===id);if(!item)return;if(!myLibrary.some(x=>x.id===id)){myLibrary.unshift({...item,ownedAt:Date.now()});log(`Purchased ${item.name} in ${live()?'Live':'Demo'} mode`);render()}}
function cancelListing(id){const x=myListings.find(v=>v.id===id);myListings=myListings.filter(v=>v.id!==id);log(`Cancelled listing ${x?.name||'item'}`);render()}
function addListing(){const price=Number($('list-price').value);if(!(price>0))return;const item={id:`user-${Date.now()}`,name:$('name-input').value.trim()||'My HyperScan',category:$('category').value,rarity:'Creator',price,icon:'✦',seller:'You',created:Date.now()};myListings.unshift(item);log(`Listed ${item.name} for ${price.toFixed(3)} MATIC`);render()}
function initStage(){const el=$('stage');scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(50,el.clientWidth/el.clientHeight,.1,100);camera.position.set(0,0,4);renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(el.clientWidth,el.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;el.appendChild(renderer.domElement);scene.add(new THREE.AmbientLight(0xffffff,2));const light=new THREE.PointLight(0x67e8f9,30,10);light.position.set(2,2,3);scene.add(light);animate();window.addEventListener('resize',()=>{camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight)})}
function buildVoxelPreview(){if(mesh)scene.remove(mesh);const group=new THREE.Group(),d=Number($('detail').value),count=Math.min(900,d*d*2);for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,r=Math.pow(Math.random(),.55)*1.35,y=(Math.random()-.5)*2.2*(1-r/1.7);const x=Math.cos(a)*r,z=Math.sin(a)*r;const g=new THREE.SphereGeometry(.035+Math.random()*.035,5,5);const m=new THREE.MeshStandardMaterial({color:new THREE.Color().setHSL(.52+Math.random()*.18,.85,.55),emissive:0x083344,emissiveIntensity:1.8});const p=new THREE.Mesh(g,m);p.position.set(x,y,z);group.add(p)}mesh=group;scene.add(group);$('stage-hint').hidden=true;$('voxel-count').textContent=count;$('mesh-tris').textContent=count*20;$('confidence').textContent=`${$('fusion').value}%`}
function animate(){requestAnimationFrame(animate);if(mesh){mesh.rotation.y+=.003;mesh.rotation.x=Math.sin(Date.now()*.0003)*.08}renderer.render(scene,camera)}
async function startCamera(){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});const v=$('camera-video');v.hidden=false;v.srcObject=stream;await v.play();$('scan-state').textContent='SCANNING';$('wallet-status').textContent='RGB camera active';let frames=0;frameTimer=setInterval(()=>{$('frame-count').textContent=++frames;buildVoxelPreview()},400)}catch(e){$('scan-state').textContent='CAMERA BLOCKED';$('stage-hint').textContent='Camera permission is required. Use Voxel Preview instead.'}}
function stopCamera(){if(frameTimer)clearInterval(frameTimer);if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;$('camera-video').hidden=true;$('scan-state').textContent='READY'}
function exportGLB(){if(!mesh)buildVoxelPreview();const exporter=new GLTFExporter();exporter.parse(mesh,data=>{const blob=new Blob([data],{type:'model/gltf-binary'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(`${($('name-input').value||'hyperscan').replace(/[^a-z0-9_-]/gi,'_')}.glb`);a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);log(`Exported ${$('name-input').value||'HyperScan'} as GLB`)},err=>console.error(err),{binary:true});}
function bind(){document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()}));['market-search','market-category','market-sort'].forEach(id=>$(id).addEventListener('input',render));$('start-camera').onclick=startCamera;$('stop-camera').onclick=stopCamera;$('generate-preview').onclick=buildVoxelPreview;$('export-glb').onclick=exportGLB;$('detail').oninput=e=>$('detail-value').textContent=e.target.value;$('fusion').oninput=e=>$('fusion-value').textContent=`${e.target.value}%`;$('apply-settings').onclick=()=>{$('model-name').textContent=$('name-input').value||'HyperScan';buildVoxelPreview()};$('list-model').onclick=()=>{$('list-dialog').showModal()};$('list-form').addEventListener('submit',e=>{e.preventDefault();addListing();$('list-dialog').close()})}
load();$('market-mode-badge').textContent=live()?'Live':'Demo';$('market-mode-badge').className=`badge ${live()?'live':'demo'}`;initStage();bind();render();buildVoxelPreview();