import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {GLTFExporter} from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/exporters/GLTFExporter.js';
import {CONFIG} from './config.js';

const KEY='hyperstream_market_v2';
const demoListings=[
{id:'m1',name:'Neon Relic',category:'Artifact',rarity:'EPIC',price:.08,icon:'◈',seller:'HYPERSTREAM',created:Date.now()-900000},
{id:'m2',name:'Quantum Bloom',category:'Hologram',rarity:'RARE',price:.12,icon:'✦',seller:'HYPERSTREAM',created:Date.now()-3600000},
{id:'m3',name:'Voxel Fox',category:'Creature',rarity:'LEGENDARY',price:.25,icon:'◉',seller:'HYPERSTREAM',created:Date.now()-7200000},
{id:'m4',name:'Dimensional Strata',category:'Environment',rarity:'EPIC',price:.18,icon:'◇',seller:'HYPERSTREAM',created:Date.now()-86400000},
{id:'m5',name:'Chrome Node',category:'Voxel',rarity:'COMMON',price:.04,icon:'⬡',seller:'HYPERSTREAM',created:Date.now()-172800000}];
let myLibrary=[],myListings=[],activityFeed=[];
let scene,camera3d,renderer,mesh,stream=null,raf=0,scanTimer=0,scanStart=0,frames=0,points=0,facing='environment',cameraReady=false;
const $=id=>document.getElementById(id);
const live=()=>Boolean(CONFIG.contractAddress&&((CONFIG.pinataJwt)||(CONFIG.pinataApiKey&&CONFIG.pinataSecretKey)));
function persist(){try{localStorage.setItem(KEY,JSON.stringify({myLibrary,myListings,activityFeed}))}catch{}}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');myLibrary=x.myLibrary||[];myListings=x.myListings||[];activityFeed=x.activityFeed||[]}catch{}}
function relative(ts){const s=Math.max(1,Math.floor((Date.now()-ts)/1000));if(s<60)return s+'s ago';const m=Math.floor(s/60);if(m<60)return m+'m ago';const h=Math.floor(m/60);if(h<24)return h+'h ago';return Math.floor(h/24)+'d ago'}
function log(text){activityFeed.unshift({text,time:Date.now()});activityFeed=activityFeed.slice(0,100);persist()}
function allListings(){return [...demoListings,...myListings]}
function empty(t){$('market-empty').hidden=false;$('market-empty').textContent=t}
function card(x,label,fn){const c=document.createElement('article');c.className='market-card';const t=document.createElement('div');t.className='card-thumb';t.textContent=x.icon||'✦';const b=document.createElement('div');b.className='card-body';const n=document.createElement('div');n.className='card-title';n.textContent=x.name;const m=document.createElement('div');m.className='card-meta';const a=document.createElement('span');a.textContent=x.category;const r=document.createElement('span');r.className='rarity';r.textContent=x.rarity||'RARE';m.append(a,r);const f=document.createElement('div');f.className='card-foot';const p=document.createElement('span');p.className='price';p.textContent=Number(x.price).toFixed(3)+' MATIC';const q=document.createElement('button');q.className='action small primary';q.textContent=label;q.onclick=fn;f.append(p,q);b.append(n,m,f);c.append(t,b);return c}
function render(){const tab=document.querySelector('.tab.active')?.dataset.tab||'browse';$('browse-tools').style.display=tab==='browse'?'grid':'none';const list=$('market-list');list.textContent='';$('market-empty').hidden=true;if(tab==='browse')renderBrowse(list);if(tab==='listings')renderMine(list);if(tab==='library')renderLibrary(list);if(tab==='activity')renderActivity(list);$('listing-count').textContent=tab==='browse'?list.children.length+' ITEMS':''}
function renderBrowse(list){let a=allListings();const q=$('market-search').value.trim().toLowerCase(),cat=$('market-category').value,s=$('market-sort').value;a=a.filter(x=>(!q||x.name.toLowerCase().includes(q)||x.category.toLowerCase().includes(q))&&(cat==='all'||x.category===cat));a.sort((x,y)=>s==='price-low'?x.price-y.price:s==='price-high'?y.price-x.price:s==='name'?x.name.localeCompare(y.name):y.created-x.created);a.forEach(x=>list.append(card(x,live()?'BUY':'BUY DEMO',()=>buy(x.id))))}
function renderMine(list){if(!myListings.length)return empty('NO ACTIVE LISTINGS. Create one from the current scan.');myListings.forEach(x=>list.append(card(x,'CANCEL',()=>cancelListing(x.id))))}
function renderLibrary(list){if(!myLibrary.length)return empty('YOUR DIGITAL LIBRARY IS EMPTY.');myLibrary.forEach(x=>list.append(card(x,'OWNED',()=>{})))}
function renderActivity(list){if(!activityFeed.length)return empty('NO ACTIVITY RECORDED.');activityFeed.forEach(x=>{const r=document.createElement('div');r.className='activity-item';const a=document.createElement('b');a.textContent=x.text;const b=document.createElement('span');b.textContent=relative(x.time);r.append(a,b);list.append(r)})}
function buy(id){const x=allListings().find(v=>v.id===id);if(!x||myLibrary.some(v=>v.id===id))return;myLibrary.unshift({...x,ownedAt:Date.now()});log('Purchased '+x.name+' · '+(live()?'LIVE':'DEMO'));render()}
function cancelListing(id){const x=myListings.find(v=>v.id===id);myListings=myListings.filter(v=>v.id!==id);log('Cancelled '+(x?.name||'listing'));render()}
function addListing(){const price=Number($('list-price').value);if(!(price>0))return;const x={id:'user-'+Date.now(),name:$('name-input').value.trim()||'Quantum Object',category:$('category').value,rarity:'CREATOR',price,icon:'✦',seller:'YOU',created:Date.now()};myListings.unshift(x);log('Listed '+x.name+' for '+price.toFixed(3)+' MATIC');render()}

function init3d(){const el=$('stage');scene=new THREE.Scene();camera3d=new THREE.PerspectiveCamera(45,el.clientWidth/el.clientHeight,.1,100);camera3d.position.z=4;renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(el.clientWidth,el.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.domElement.style.position='absolute';renderer.domElement.style.inset='0';renderer.domElement.style.pointerEvents='none';el.appendChild(renderer.domElement);scene.add(new THREE.AmbientLight(0xffffff,1.8));const l=new THREE.PointLight(0x62f6ff,35,12);l.position.set(2,2,4);scene.add(l);window.addEventListener('resize',()=>{camera3d.aspect=el.clientWidth/el.clientHeight;camera3d.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight)});animate()}
function animate(){raf=requestAnimationFrame(animate);if(mesh){mesh.rotation.y+=.0025;mesh.rotation.x=Math.sin(Date.now()*.00035)*.04}renderer.render(scene,camera3d)}

function buildVolume(){if(mesh)scene.remove(mesh);const g=new THREE.Group(),detail=Number($('detail').value),count=Math.min(1300,detail*detail+200);for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,rad=Math.pow(Math.random(),.65)*1.25,y=(Math.random()-.5)*2.1*(1-rad/1.8),x=Math.cos(a)*rad,z=Math.sin(a)*rad;const s=.018+Math.random()*.032;const geo=new THREE.BoxGeometry(s,s,s);const mat=new THREE.MeshStandardMaterial({color:new THREE.Color().setHSL(.48+Math.random()*.16,.9,.55),emissive:new THREE.Color(0x092a38),emissiveIntensity:1.7,roughness:.4});const p=new THREE.Mesh(geo,mat);p.position.set(x,y,z);g.add(p)}mesh=g;scene.add(g);$('voxel-count').textContent=count.toLocaleString();$('mesh-tris').textContent=(count*12).toLocaleString();$('stage-message').style.display='none'}

function updateCanvas(){const v=$('camera-video'),c=$('scan-canvas');if(!cameraReady||v.readyState<2)return;const w=c.width=v.videoWidth||1280,h=c.height=v.videoHeight||720,ctx=c.getContext('2d');ctx.clearRect(0,0,w,h);ctx.drawImage(v,0,0,w,h);const step=Math.max(10,Math.floor(42-Number($('detail').value)/2));const data=ctx.getImageData(0,0,w,h).data;ctx.clearRect(0,0,w,h);ctx.globalCompositeOperation='lighter';let local=0;for(let y=step/2;y<h;y+=step){for(let x=step/2;x<w;x+=step){const i=(Math.floor(y)*w+Math.floor(x))*4,l=.299*data[i]+.587*data[i+1]+.114*data[i+2];if(l<35)continue;const alpha=Math.min(.8,Math.max(.08,(l-30)/300));ctx.fillStyle=`rgba(${70+Math.floor(l/3)},${220+Math.floor(l/7)},255,${alpha})`;const rr=1+Math.floor(l/90);ctx.fillRect(x,y,rr,rr);local++}}points=local;frames++;$('frame-count').textContent=frames.toLocaleString();$('voxel-count').textContent=Math.max(points*2,1).toLocaleString();$('confidence').textContent=Math.min(99,Math.round(38+Number($('fusion').value)*.58))+'%';$('scan-resolution').textContent=w+'×'+h}
function scanLoop(){if(!cameraReady)return;updateCanvas();const sec=Math.max(0,(performance.now()-scanStart)/1000);$('scan-time').textContent=new Date(sec*1000).toISOString().slice(14,19);$('fps').textContent=Math.round(frames/Math.max(sec,.1))+' FPS';requestAnimationFrame(scanLoop)}

async function openCamera(){if(!navigator.mediaDevices?.getUserMedia){setCameraError('CAMERA API UNAVAILABLE. Use HTTPS or localhost.');return}stopCamera(false);try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{exact:facing},width:{ideal:1280},height:{ideal:720}},audio:false});const v=$('camera-video');v.srcObject=stream;v.muted=true;v.playsInline=true;await v.play();cameraReady=true;$('stage-message').style.display='none';$('scan-state').textContent='SCANNING';$('connection').textContent='CAMERA LINK ACTIVE';$('capture-mode').textContent=facing==='environment'?'REAR RGB':'FRONT RGB';$('camera-side').textContent=facing==='environment'?'REAR':'FRONT';$('camera-label').textContent=(facing==='environment'?'REAR':'FRONT')+' CAMERA';scanStart=performance.now();frames=0;scanLoop();clearInterval(scanTimer);scanTimer=setInterval(buildVolume,1800)}catch(e){cameraReady=false;setCameraError(e.name==='NotAllowedError'?'CAMERA PERMISSION DENIED. Allow camera access in browser settings.':e.name==='NotFoundError'?'NO CAMERA FOUND.':'CAMERA ERROR: '+e.message)}}
function setCameraError(t){$('scan-state').textContent='CAMERA ERROR';$('connection').textContent='CAMERA LINK FAILED';$('stage-message').style.display='grid';$('stage-message').querySelector('b').textContent=t;$('stage-message').querySelector('span').textContent='Try HTTPS, allow permissions, then press START SCAN again.'}
function stopCamera(reset=true){cameraReady=false;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}clearInterval(scanTimer);$('camera-video').srcObject=null;if(reset){$('scan-state').textContent='STANDBY';$('connection').textContent='SYSTEM READY';$('fps').textContent='0 FPS'}}
function flipCamera(){facing=facing==='environment'?'user':'environment';openCamera()}
function exportGLB(){if(!mesh)buildVolume();const ex=new GLTFExporter();ex.parse(mesh,data=>{const blob=new Blob([data],{type:'model/gltf-binary'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(($('name-input').value||'hyperstream-scan').replace(/[^a-z0-9_-]/gi,'_'))+'.glb';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);log('Exported '+($('name-input').value||'scan')+' as GLB')},console.error,{binary:true})}
function bind(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()});['market-search','market-category','market-sort'].forEach(id=>$(id).addEventListener('input',render));$('start-camera').onclick=openCamera;$('stop-camera').onclick=()=>stopCamera();$('flip-camera').onclick=flipCamera;$('generate-preview').onclick=buildVolume;$('export-glb').onclick=exportGLB;$('detail').oninput=e=>{$('detail-value').textContent=e.target.value};$('fusion').oninput=e=>$('fusion-value').textContent=e.target.value+'%';$('apply-settings').onclick=()=>{$('model-name').textContent=$('name-input').value||'QUANTUM OBJECT';buildVolume()};$('list-model').onclick=()=>$('list-dialog').showModal();$('list-form').addEventListener('submit',e=>{e.preventDefault();addListing();$('list-dialog').close()})}

load();$('market-mode-badge').textContent=live()?'LIVE':'DEMO';$('market-mode-badge').className='badge '+(live()?'live':'demo');init3d();bind();render();buildVolume();
