/* HyperStream Wallet Core v10: direct provider + MetaMask mobile + browser QR portal */
const SEPOLIA={chainId:'0xaa36a7',chainName:'Sepolia',nativeCurrency:{name:'Sepolia Ether',symbol:'ETH',decimals:18},rpcUrls:['https://rpc.sepolia.org'],blockExplorerUrls:['https://sepolia.etherscan.io']};
const $=id=>document.getElementById(id);
const isIOS=()=>/iPhone|iPad|iPod/i.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
const inMM=()=>/MetaMaskMobile/i.test(navigator.userAgent);
const short=a=>a?`${a.slice(0,8)}…${a.slice(-6)}`:'';
function setStatus(t,e=false){$('walletStatus')&&( $('walletStatus').textContent=t,$('walletStatus').classList.toggle('error',e));$('status')&&( $('status').textContent=t,$('status').classList.toggle('error',e));}
function target(){return location.href.split('#')[0]}
function mmLink(){return 'https://metamask.app.link/dapp/'+location.host+location.pathname+location.search}
function portal(){const p=$('walletPortal');if(!p)return;p.classList.add('active');const url=mmLink();const q=$('walletQR');if(q){q.innerHTML='';const img=document.createElement('img');img.src='https://api.qrserver.com/v1/create-qr-code/?size=560x560&margin=10&data='+encodeURIComponent(url);img.alt='HyperStream MetaMask wallet QR';q.appendChild(img)}$('walletPortalUrl')&&($('walletPortalUrl').textContent=location.host+location.pathname);setStatus('PORTAL ONLINE · SCAN WITH METAMASK');}
function closePortal(){$('walletPortal')?.classList.remove('active')}
async function sep(p){const c=String(await p.request({method:'eth_chainId'})).toLowerCase();if(c===SEPOLIA.chainId)return;try{await p.request({method:'wallet_switchEthereumChain',params:[{chainId:SEPOLIA.chainId}]})}catch(e){if(e?.code!==4902)throw e;await p.request({method:'wallet_addEthereumChain',params:[SEPOLIA]})}if(String(await p.request({method:'eth_chainId'})).toLowerCase()!==SEPOLIA.chainId)throw Error('Switch wallet to Sepolia.')}
function linked(b,a,p){window.walletProvider=p;window.walletAddress=a;window.walletSession={accounts:[a],chainId:SEPOLIA.chainId};window.walletClient=p;window.hyperstreamSetWallet?.(a);closePortal();if(b){b.disabled=false;b.textContent='WALLET LINKED ✓'}setStatus('WALLET LINKED ✓\n'+short(a)+' · SEPOLIA')}
async function connectWallet(){const b=$('connectWalletBtn');if(b){b.disabled=true;b.textContent='SYNCING…'}try{const p=window.ethereum;if(!p){if(isIOS()&&!inMM()){setStatus('OPENING METAMASK…');location.href=mmLink();return}portal();if(b){b.disabled=false;b.textContent='OPEN WALLET PORTAL'}return}setStatus('WALLET SIGNAL DETECTED · AUTHORIZING…');const a=(await p.request({method:'eth_requestAccounts'}))?.[0];if(!a)throw Error('No account returned.');await sep(p);linked(b,a,p);p.on?.('accountsChanged',a=>a?.length?linked(b,a[0],p):(window.walletProvider=null,setStatus('WALLET DISCONNECTED')));p.on?.('chainChanged',c=>String(c).toLowerCase()===SEPOLIA.chainId?setStatus('WALLET LINKED ✓ · SEPOLIA'):setStatus('NETWORK CHANGED · SWITCH TO SEPOLIA',true));}catch(e){console.error(e);setStatus('LINK FAILED · '+(e?.message||e),true);if(b){b.disabled=false;b.textContent='RETRY LINK'}}}
window.walletClient=null;window.walletProvider=null;window.walletSession=null;window.walletAddress=null;window.reownConnect=connectWallet;window.connectWallet=connectWallet;
window.addEventListener('DOMContentLoaded',()=>{const b=$('connectWalletBtn');b?.addEventListener('click',connectWallet);$('walletPortalClose')?.addEventListener('click',closePortal);$('walletPortalOpen')?.addEventListener('click',()=>location.href=mmLink());});
