/* HyperStream 3D - Quest-first direct MetaMask connector */
const SEPOLIA={chainId:'0xaa36a7',chainName:'Sepolia',nativeCurrency:{name:'Sepolia Ether',symbol:'ETH',decimals:18},rpcUrls:['https://rpc.sepolia.org'],blockExplorerUrls:['https://sepolia.etherscan.io']};
const $=id=>document.getElementById(id);
function status(t,e=false){const s=$('status');if(s){s.textContent=t;s.className='status'+(e?' error':'')}const w=$('walletStatus');if(w){w.textContent=t;w.className='walletstatus'+(e?' error':'')}}
function short(a){return a?`${a.slice(0,8)}...${a.slice(-6)}`:''}
async function ensureSepolia(p){const c=await p.request({method:'eth_chainId'});if(String(c).toLowerCase()===SEPOLIA.chainId)return;try{await p.request({method:'wallet_switchEthereumChain',params:[{chainId:SEPOLIA.chainId}]})}catch(e){if(e?.code!==4902)throw e;await p.request({method:'wallet_addEthereumChain',params:[SEPOLIA]})}const a=await p.request({method:'eth_chainId'});if(String(a).toLowerCase()!==SEPOLIA.chainId)throw Error('Please switch MetaMask to Sepolia and try again.')}
function setConnected(b,a,p){window.walletProvider=p;window.walletAddress=a;window.hyperstreamSetWallet?.(a);if(b){b.disabled=false;b.textContent='WALLET CONNECTED'}status(`MetaMask connected\n${short(a)}\nSepolia`)}
async function connectWallet(){const b=$('connectWalletBtn');if(b){b.disabled=true;b.textContent='CONNECTING...'}try{const p=window.ethereum;if(!p)throw Error("MetaMask was not detected. On Quest, use a browser that exposes the MetaMask wallet provider.");status('MetaMask detected. Requesting wallet...');const ac=await p.request({method:'eth_requestAccounts'});const a=ac?.[0];if(!a)throw Error('MetaMask returned no wallet account.');status('Wallet connected. Checking network...');await ensureSepolia(p);window.walletProvider=p;window.walletAddress=a;window.walletSession={accounts:[a],chainId:SEPOLIA.chainId};window.walletClient=p;setConnected(b,a,p);p.on?.('accountsChanged',accountsChanged);p.on?.('chainChanged',chainChanged)}catch(e){console.error(e);status('Wallet connection failed.\n'+(e?.message||String(e)),true);if(b){b.disabled=false;b.textContent='CONNECT WALLET'}}}
function accountsChanged(a){if(!a?.length){window.walletAddress=null;window.walletProvider=null;window.walletSession=null;if($('wallet'))$('wallet').textContent='';if($('walletStatus'))$('walletStatus').textContent='Wallet disconnected';return}window.walletAddress=a[0];window.hyperstreamSetWallet?.(a[0]);status(`MetaMask account changed\n${short(a[0])}`)}
function chainChanged(c){if(String(c).toLowerCase()===SEPOLIA.chainId)status('MetaMask connected\nSepolia');else status('MetaMask is connected, but the network is not Sepolia. Switch to Sepolia before minting.',true)}
window.walletClient=null;window.walletProvider=null;window.walletSession=null;window.walletAddress=null;window.reownConnect=connectWallet;window.connectWallet=connectWallet;
window.addEventListener('DOMContentLoaded',()=>{const b=$('connectWalletBtn');if(!b)return;b.type='button';b.addEventListener('click',connectWallet)});
